######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 26 10:58:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DiffWidget.h Parser.h
SOURCES += DiffWidget.cpp main.cpp Parser.cpp
QT += xml
